

var delegateScale = d3.scaleLinear()
  .domain([0, .50, 1])
  .range(["white", "#2968F5", "#002E66"]);



d3.csv("delegates.csv", function (error, data) {




  var svg = d3.select("#delegatesover").append("svg")
    .attr("viewBox", "-50 0 1050 3380")
    .append('g')




  var svgLegend = svg.append('g')
    .attr('class', 'gLegend')
    .attr("transform", "translate(" + 0 + "," + 90 + ")")



  var legend = svgLegend.selectAll('.legend')
    .data(data)
    .enter().append('g')
    .attr("class", "legend")
    .attr("transform", function (d, i) { return "translate(0," + i * 40 + ")" })



  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 20)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 500)
    .text(d => d.date)
    .attr("text-anchor", "start")



  legend.append("a")
    .attr("xlink:href", d => d.state=="-->"?"":d.state)
    .append("text")
    .attr("class", "statelink")
    .attr("x", 300)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", "12pt")
    .attr("font-weight", 700)
    .text(d => d.state)
    .attr("text-anchor", "middle")
  

  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 100)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 12)
    .attr("font-weight", 700)
    .text(d => d.thru)
    .attr("text-anchor", "start")

  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 425)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 700)
    .text(d => d.delegates)
    .attr("text-anchor", "middle")







  legend.append("rect")
    .attr("x", 475)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.bidenper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 525)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.bloombergper))
    .style("opacity", .8)
  legend.append("rect")
    .attr("x", 575)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.bookerper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 625)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.buttigiegper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 675)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.klobucharper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 725)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.sandersper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 775)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.steyerper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 825)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.warrenper))
    .style("opacity", .8)

  legend.append("rect")
    .attr("x", 875)
    .attr("y", -30)
    .attr("width", 50)
    .attr("height", 40)
    .style("fill", d => delegateScale(d.yangper))
    .style("opacity", .8)

  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 500)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.biden == 0 ? "" : d.biden)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 550)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.bloomberg == 0 ? "" : d.bloomberg)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 600)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.booker == 0 ? "" : d.booker)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 650)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.buttigieg == 0 ? "" : d.buttigieg)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 700)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.klobuchar == 0 ? "" : d.klobuchar)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 750)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.sanders == 0 ? "" : d.sanders)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 800)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.steyer == 0 ? "" : d.steyer)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 850)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.warren == 0 ? "" : d.warren)
    .attr("text-anchor", "middle")
  legend.append("text")
    .attr("class", "legend-text")
    .attr("x", 900)
    .attr("y", -5)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 700)
    .text(d => d.yang == 0 ? "" : d.yang)
    .attr("text-anchor", "middle")



  svg.append("text")
    .attr("x", 20)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 500)
    .text("Date")
    .attr("text-anchor", "start")


  svg.append("text")
    .attr("x", 300)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 15)
    .attr("font-weight", 500)
    .text("State")
    .attr("text-anchor", "middle")



  svg.append("text")
    .attr("x", 425)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 12)
    .attr("font-weight", 500)
    .text("Delegates")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 500)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Biden")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 550)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Bloomberg")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 600)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Booker")
    .attr("text-anchor", "middle")

  svg.append("text")
    .attr("x", 650)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Buttigieg")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 700)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Klobuchar")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 750)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Sanders")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 800)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Steyer")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 850)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Warren")
    .attr("text-anchor", "middle")
  svg.append("text")
    .attr("x", 900)
    .attr("y", 40)
    .style("fill", "Black")
    .style("font-size", 10)
    .attr("font-weight", 500)
    .text("Yang")
    .attr("text-anchor", "middle")

  legend.append("line")
    .attr("x1", 0)
    .attr("x2", 950)
    .attr("y1", -30)
    .attr("y2", -30)
    .attr("stroke", d => d.date == "" ? "#E2E2E2" : "black")
    .attr("stroke-width", d => d.date == "" ? 1 : 2)




  svg.append("line")
    .attr("x1", 0)
    .attr("x2", 950)
    .attr("y1", 60)
    .attr("y2", 60)
    .attr("stroke-width", 2)
    .attr("stroke", "black")

  
});